services:
  back:
    # image: clojure:openjdk-18-tools-deps-bullseye
    # working_dir: /usr/src/app/back
    build: ./back
    command: "clj -X:dev"
    # command: bash -c "java -jar back.jar server-with-migration"
    volumes:
      - ./back:/usr/src/app/back
      - ./common:/usr/src/app/common
      - ./filestorage:/usr/src/app/filestorage
      - ./front:/usr/src/app/front
      - .volumes/m2:/root/.m2
    ports:
      - "3000:3000"
      - "59595:59595"
    environment:
      PORT: 3000
      DATABASE_URL: mysql://mariadb:3306/server_practice?user=maria-user&password=maria-pass
    depends_on:
      - mariadb
  front:
    # image: clojure:openjdk-18-tools-deps-bullseye
    # working_dir: /usr/src/app/front
    build: ./front
    command: bash -c "yarn && clj -M:dev"
    # command: bash -c "yarn && clj -M -m cljs.main -co build.edn -v --watch ./src -c"
    # command: bash -c "yarn && clj -M -m cljs.main -co build.edn -c"
    volumes:
      - ./front:/usr/src/app/front
      - ./common:/usr/src/app/common
      - .volumes/m2:/root/.m2
    ports:
      - "9630:9630" # web socket for shadow js
  mariadb:
    image: "mariadb:11.4"
    volumes:
      - .volumes/mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: maria-root-pass
      MARIADB_DATABASE: server_practice
      MARIADB_USER: maria-user
      MARIADB_PASSWORD: maria-pass
