services:
  back-test:
    build: ./back
    command: "clj -X:dev"
    volumes:
      - ./back:/usr/src/app/back
      - ./filestorage-test:/usr/src/app/filestorage
      - ./front:/usr/src/app/front
      - .volumes/m2:/root/.m2
    ports:
      - "3000:3000"
      - "59595:59595"
    environment:
      PORT: 3000
      DATABASE_URL: mysql://mariadb-test:3306/test_db?user=maria-user&password=maria-pass
    depends_on:
      - mariadb-test
  front-test:
    build: ./front
    command: bash -c "yarn && clj -M:dev"
    volumes:
      - ./front:/usr/src/app/front
      - .volumes/m2:/root/.m2
    ports:
      - "9630:9630" # web socket for shadow js
  mariadb-test:
    image: "mariadb:11.4"
    volumes:
      - .volumes/mariadb-test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: maria-root-pass
      MYSQL_DATABASE: test_db
      MYSQL_USER: maria-user
      MYSQL_PASSWORD: maria-pass
